version: '3.9'

services:
  dashboard:
    build:
      context: ./dashboard
      dockerfile: ../docker/react/Dockerfile
    tty: true
    stdin_open: true
    environment:
      CHOKIDAR_USEPOLLING: true
    volumes:
      - ./dashboard:/usr/src/app:cached
      - /usr/src/app/node_modules
    command: sh -c "yarn start"
    ports:
      - "3000:3000"
  api:
    build:
      context: ./api
      dockerfile: ../docker/flask/Dockerfile
    environment:
      FLASK_APP: app
      FLASK_ENV: development
    volumes:
      - ./api:/usr/src/app:cached
    command: sh -c "flask run --host=0.0.0.0"
    ports:
      - "5001:5000"
